// tangga nada sebagai selisih semitone dari akar, bukan daftar frekuensi
// tetap, supaya root per tema bisa berbeda tanpa mengubah pola melodi
const SCALES = {
  majorPenta: [0, 2, 4, 7, 9],
  minorPenta: [0, 3, 5, 7, 10],
  dorian: [0, 2, 3, 5, 7, 9, 10],
  aeolian: [0, 2, 3, 5, 7, 8, 10],
  harmonicMinor: [0, 2, 3, 5, 7, 8, 11],
  lydian: [0, 2, 4, 6, 7, 9, 11],
}

// tiap tema: dua pola (bas + melodi) berisi indeks tangga nada atau null
// (jeda). Karakter musik disesuaikan suasana tiap permainan: ceria dan cepat
// untuk Tic Tac Toe, tegang untuk Minesweeper, tenang untuk Sudoku, dst.
export const MUSIC_THEMES = {
  menu: {
    bpm: 96,
    root: 220,
    scale: SCALES.majorPenta,
    bassWave: 'triangle',
    leadWave: 'sine',
    bassOctave: -1,
    leadOctave: 0,
    bassGain: 0.07,
    leadGain: 0.045,
    bassSustain: 3.2,
    leadSustain: 1.1,
    bassPattern: [0, null, null, null, 3, null, null, null],
    leadPattern: [4, null, 2, null, 0, null, 2, null, 4, null, 2, null, 0, null, null, null],
  },
  tictactoe: {
    bpm: 134,
    root: 262,
    scale: SCALES.majorPenta,
    bassWave: 'triangle',
    leadWave: 'square',
    bassOctave: -1,
    leadOctave: 0,
    bassGain: 0.065,
    leadGain: 0.036,
    bassSustain: 0.85,
    leadSustain: 0.32,
    bassPattern: [0, null, 0, null, 3, null, 2, null],
    leadPattern: [4, null, null, 3, 2, null, null, 0, 2, null, null, 4, 3, null, null, null],
  },
  connectfour: {
    bpm: 120,
    root: 196,
    scale: SCALES.minorPenta,
    bassWave: 'triangle',
    leadWave: 'square',
    bassOctave: -1,
    leadOctave: 0,
    bassGain: 0.075,
    leadGain: 0.038,
    bassSustain: 0.5,
    leadSustain: 0.4,
    bassPattern: [0, 0, 3, 0, 0, 0, 2, 0],
    leadPattern: [null, 4, null, null, 3, null, 4, null, null, 2, null, null, 0, null, null, null],
  },
  othello: {
    bpm: 76,
    root: 174,
    scale: SCALES.lydian,
    bassWave: 'sine',
    leadWave: 'triangle',
    bassOctave: -1,
    leadOctave: 1,
    bassGain: 0.07,
    leadGain: 0.032,
    bassSustain: 3.6,
    leadSustain: 2.2,
    bassPattern: [0, null, null, null, 4, null, null, null],
    leadPattern: [null, null, 6, null, null, null, null, null, 5, null, null, null, null, null, null, null],
  },
  minesweeper: {
    bpm: 100,
    root: 220,
    scale: SCALES.aeolian,
    bassWave: 'square',
    leadWave: 'triangle',
    bassOctave: -1,
    leadOctave: 0,
    bassGain: 0.05,
    leadGain: 0.028,
    bassSustain: 0.18,
    leadSustain: 0.9,
    bassPattern: [0, null, null, null, 0, null, null, null],
    leadPattern: [null, null, null, 1, null, null, 5, null, null, null, null, 3, null, null, null, null],
  },
  sudoku: {
    bpm: 60,
    root: 196,
    scale: SCALES.dorian,
    bassWave: 'sine',
    leadWave: 'sine',
    bassOctave: -1,
    leadOctave: 1,
    bassGain: 0.065,
    leadGain: 0.03,
    bassSustain: 4.5,
    leadSustain: 3.5,
    bassPattern: [0, null, null, null, null, null, null, null],
    leadPattern: [null, null, null, null, 2, null, null, null, null, null, null, null, 4, null, null, null],
  },
  chess: {
    bpm: 84,
    root: 220,
    scale: SCALES.harmonicMinor,
    bassWave: 'triangle',
    leadWave: 'triangle',
    bassOctave: -1,
    leadOctave: 0,
    bassGain: 0.07,
    leadGain: 0.04,
    bassSustain: 1.6,
    leadSustain: 0.9,
    bassPattern: [0, null, null, null, 3, null, null, null],
    leadPattern: [0, null, 2, null, 3, null, 5, null, 6, null, 5, null, 3, null, 2, null],
  },
}
